const { app, BrowserWindow, Menu, dialog } = require('electron');
const path = require('path');
const fs = require('fs');

// Global error handlers to prevent silent crashes
process.on('uncaughtException', (error) => {
  console.error('Uncaught Exception:', error);
  dialog.showErrorBox(
    'DielineForge Startup Error',
    `An unexpected error occurred during application startup:\n\n${error.stack || error.message || error}`
  );
});

process.on('unhandledRejection', (reason) => {
  console.error('Unhandled Rejection:', reason);
});

let mainWindow = null;

// Ensure single instance on Windows
const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
  // If another instance exists, exit cleanly
  app.quit();
} else {
  app.on('second-instance', (event, commandLine, workingDirectory) => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });

  app.whenReady().then(() => {
    try {
      createWindow();
    } catch (err) {
      dialog.showErrorBox('Initialization Error', String(err && err.stack ? err.stack : err));
    }
  });
}

function isValidAppHtml(filePath) {
  try {
    if (!fs.existsSync(filePath)) return false;
    const content = fs.readFileSync(filePath, 'utf8');
    // Ensure it is the genuine Angular CAD app, not a server cookie check or redirect page
    return content.includes('app-root') || content.includes('DielineForge');
  } catch {
    return false;
  }
}

function resolveIndexPath() {
  const appPath = app.getAppPath();
  const candidates = [
    // Prioritize pure Client-Side Rendering (CSR) templates generated by Angular
    path.join(appPath, 'dist/app/browser/index.csr.html'),
    path.join(appPath, 'dist/browser/index.csr.html'),
    path.join(appPath, 'dist/app/browser/index.html'),
    path.join(appPath, 'dist/browser/index.html'),
    path.join(appPath, 'dist/index.csr.html'),
    path.join(appPath, 'dist/index.html'),
    path.join(appPath, 'dist/app/index.html'),
    path.join(__dirname, '../dist/app/browser/index.csr.html'),
    path.join(__dirname, '../dist/app/browser/index.html'),
    path.join(__dirname, '../dist/browser/index.csr.html'),
    path.join(__dirname, '../dist/browser/index.html'),
    path.join(__dirname, '../dist/index.html'),
    path.join(__dirname, 'dist/app/browser/index.csr.html'),
    path.join(__dirname, 'dist/app/browser/index.html')
  ];

  // First pass: find a candidate that is verified to contain Angular's app-root
  for (const candidate of candidates) {
    if (isValidAppHtml(candidate)) {
      return candidate;
    }
  }

  // Second pass: any existing candidate
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  // Search recursively inside appPath for any index.csr.html or index.html
  function findIndexRecursive(dir, depth = 0) {
    if (depth > 4 || !fs.existsSync(dir)) return null;
    try {
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      // Search for index.csr.html first
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (!entry.isDirectory() && entry.name === 'index.csr.html' && isValidAppHtml(fullPath)) {
          return fullPath;
        }
      }
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (!entry.isDirectory() && (entry.name === 'index.html' || entry.name === 'index.csr.html') && isValidAppHtml(fullPath)) {
          return fullPath;
        }
        if (entry.isDirectory() && entry.name !== 'node_modules' && entry.name !== '.git') {
          const found = findIndexRecursive(fullPath, depth + 1);
          if (found) return found;
        }
      }
    } catch {
      // Ignore read errors
    }
    return null;
  }

  const recursiveMatch = findIndexRecursive(appPath) || findIndexRecursive(path.join(__dirname, '..'));
  if (recursiveMatch) {
    return recursiveMatch;
  }

  // Default fallback
  return path.join(appPath, 'dist/app/browser/index.html');
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 1024,
    minHeight: 700,
    title: 'DielineForge CAD - Parametric Packaging & Zünd Production',
    backgroundColor: '#0a0a0a',
    show: false, // Show gracefully once content is ready
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: false,
      webSecurity: false // Necessary for local file:// protocol and svg generation
    },
    autoHideMenuBar: false
  });

  const indexPath = resolveIndexPath();

  // Show window once ready to prevent flickering
  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  // Handle load failure with a clear native dialog only for main frame
  mainWindow.webContents.on('did-fail-load', (event, errorCode, errorDescription, validatedURL, isMainFrame) => {
    console.error('Failed to load:', errorCode, errorDescription, validatedURL, 'isMainFrame:', isMainFrame);
    if (errorCode !== -3 && isMainFrame) { // -3 is ABORTED (e.g. redirected or hash navigation)
      dialog.showErrorBox(
        'Failed to Load Application',
        `Unable to load DielineForge CAD interface.\n\nFile: ${indexPath}\nURL: ${validatedURL}\nError: ${errorDescription} (${errorCode})\n\nPlease ensure 'npm run build' was executed prior to packaging.`
      );
    }
  });

  mainWindow.webContents.on('render-process-gone', (event, details) => {
    console.error('Render process gone:', details);
    dialog.showErrorBox(
      'Renderer Crash',
      `The CAD UI process crashed: ${details.reason} (exit code: ${details.exitCode})`
    );
  });

  mainWindow.loadFile(indexPath).catch((err) => {
    console.error('loadFile caught error:', err);
    dialog.showErrorBox(
      'Startup File Missing',
      `Could not find or open ${indexPath}.\n\nError: ${err.message}`
    );
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
